CREATE TABLE CUSTOMERS(
    ID NUMBER,
    CONSTRAINT CUSTOMER_ID PRIMARY KEY (ID),
    COMPANY_NAME NVARCHAR2(50),
    CONTACT_NAME NVARCHAR2(20),
    CONTACT_TITLE NVARCHAR2(20),
    ADDRESS NVARCHAR2(50),
    CITY NVARCHAR2(20),
    REGION NVARCHAR2(60),
    POSTAL_CODE NUMBER,
    COUNTRY NVARCHAR2(20),
    PHONE NUMBER,
    FAX NUMBER
);