CREATE TABLE SUPPLIERS(
    ID NUMBER,
    CONSTRAINT SUPPLIER_ID PRIMARY KEY (ID),
    COMPANY_NAME NVARCHAR2(50),
    CONTACT_NAME NVARCHAR2(20),
    CONTACT_TITLE NVARCHAR2(20),
    ADDRESS NVARCHAR2(50),
    CITY NVARCHAR2(20),
    REGION NVARCHAR2(60),
    POSTAL_CODE NUMBER,
    COUNTRY NVARCHAR2(20),
    PHONE NUMBER,
    FAX NUMBER,
    HOME_PAGE NVARCHAR2(500)
);