CREATE TABLE PRODUCTS(
    ID NUMBER,
    CONSTRAINT PRODUCT_ID PRIMARY KEY (ID),
    PRODUCT_NAME NVARCHAR2(20),
    SUPPLIER_ID NUMBER,
    CONSTRAINT SUPPLIER_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(ID),
    CATEGORY_ID NUMBER,
    CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
    QUANTITY_PER_UNIT NUMBER,
    UNIT_PRICE NUMBER(7,2),
    UNITS_IN_STOCK NUMBER,
    UNITS_IN_ORDER NUMBER,
    REODER_LEVEL NUMBER,
    DISCONTINUED NUMBER(1,0)
);