CREATE TABLE FORUM_POSTS(
    ID NUMBER,
    CONSTRAINT POSTS_PK PRIMARY KEY (ID),
    SUBCATEGORY_ID NUMBER,
    CONSTRAINT SUBCATEGORY_FK FOREIGN KEY (SUBCATEGORY_ID) REFERENCES FORUM_SUBCATEGORIES(ID),
    USER_ID NUMBER,
    CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    PARENT_ID NUMBER,
    CONSTRAINT PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES FORUM_POSTS(ID),
    TITLE NVARCHAR2(90),
    CONTENT CLOB,
    IS_POLL NUMBER(1,0),
    DATE_POSTS TIMESTAMP,
    IP NVARCHAR2(20)
);