CREATE TABLE FORUM_SUBCATEGORIES(
    ID NUMBER,
    CONSTRAINT SUBCATEGORIES_PK PRIMARY KEY (ID),
    CATEGORY_ID NUMBER,
    CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES FORUM_CATEGORIES(ID),
    TITLE NVARCHAR2(64),
    DESCRIPTION CLOB,
    DATE_CATEGORIES TIMESTAMP,
    IP NVARCHAR2(20)
);