CREATE TABLE ORDERS(
    ID NUMBER(4),
    CONSTRAINT ORDER_ID PRIMARY KEY (ID),
    USER_ID NUMBER UNIQUE,
    ROOM_ID NUMBER UNIQUE,
    DATE_FROM TIMESTAMP,
    DATE_TO TIMESTAMP,
    MONEY_PAID NUMBER(5,2)
);