CREATE TABLE FORUM_POLLS_OPTIONS_VOTES(
    ID NUMBER,
    CONSTRAINT POLLS_OPTIONS_VOTES_PK PRIMARY KEY (ID),
    POLL_OPTION_ID NUMBER,
    CONSTRAINT POLL_OPTION_FK FOREIGN KEY (POLL_OPTION_ID) REFERENCES FORUM_POLLS_OPTIONS(ID),
    USER_ID NUMBER,
    CONSTRAINT USER_VOTES_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    DATE_POLLS_OPTIONS_VOTES TIMESTAMP,
    IP NVARCHAR2(20)
);