CREATE TABLE FORUM_POLLS_OPTIONS(
    ID NUMBER,
    CONSTRAINT POLLS_OPTIONS_PK PRIMARY KEY (ID),
    POST_ID NUMBER,
    CONSTRAINT POST_FK FOREIGN KEY (POST_ID) REFERENCES FORUM_POSTS(ID),
    TITLE NVARCHAR2(64),
    DATE_POLLS_OPTIONS TIMESTAMP
);