CREATE TABLE MOVIE_STAT(
    MOVIE_ID NUMBER,
    CONSTRAINT MOVIE_ID_STAT PRIMARY KEY(MOVIE_ID),
    RATING NUMBER(5,1) CHECK(RATING BETWEEN 1 AND 10),
    DOMESTIC_SALES NUMBER,
    INTERNATIONAL_SALES NUMBER
);