CREATE TABLE MOVIE(
    ID NUMBER,
    CONSTRAINT MOVIE_ID PRIMARY KEY (ID),
    TITLE VARCHAR2(50) NOT NULL UNIQUE,
    DIRECTOR VARCHAR2(50) NOT NULL,
    YEAR NUMBER CHECK(YEAR BETWEEN 1900 AND 2019),
    LENGTH_MINS NUMBER CHECK(LENGTH_MINS BETWEEN 10 AND 200)
);