--by id
SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, SALESMAN.CITY
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID;

--BY CITY
SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, SALESMAN.CITY
FROM SALESMAN, CUSTOMER
WHERE SALESMAN.CITY = CUSTOMER.CITY;

--BETWEEN DATE
SELECT CUSTOMER.CUSTNAME
FROM CUSTOMER
JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
WHERE DEAL.DEAL_DATE BETWEEN TO_DATE('2017','YYYY') AND TO_DATE('2018','YYYY');

--by amount
SELECT CUSTOMER.CUSTNAME, CUSTOMER.CITY, SALESMAN.NAME, SALESMAN.CITY
FROM CUSTOMER
JOIN SALESMAN ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID AND DEAL.AMOUNT > 10000;

--sum by date
SELECT SALESMAN.NAME, SUM(DEAL.AMOUNT)
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
WHERE DEAL.DEAL_DATE BETWEEN TO_DATE('08-2017','MM-YYYY') AND TO_DATE('09-2017','MM-YYYY')
GROUP BY SALESMAN.NAME
ORDER BY 2 DESC;